---
title: "dawn"
date: "2024-06-27"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---



```{r, message=F, warning=F}
#library("devtools")  # https://github.com/linnykos/covarianceSelection
#devtools::install_github("linnylin92/covarianceSelection", subdir = "covarianceSelection")

```





```{r, message=F, warning=F, eval=F}
# step0_loading.R
#if(verbose) print("Start of step 0: Loading")

#format the brainspan dataset
load("C:/han/Dataset/20231006_PMID_33731968/NIHMS1598069-supplement-Supp_1/newGenexp.RData")
rownames(genexp) <- genexp[,1]
genexp <- genexp[,-1]
genexp <- t(genexp)
genexp <- as.data.frame(genexp) # 1340 x 16947
dim(genexp)
```




```{r, message=F, warning=F, eval=F}

#determine brain-expressed genes
#brain_expression <- covarianceSelection::brain_expression
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\brain_expression.rda")
brain_genes <- brain_expression$Gene[brain_expression$Brain_expressed != 'No']
idx <- which(colnames(genexp) %in% brain_genes)
genexp <- genexp[,idx] # 1340 x 14370
dim(genexp)
```



```{r, message=F, warning=F, eval=F}

#translate into synonyms
#vec <- covarianceSelection::symbol_synonyms(colnames(genexp), verbose = T)
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\cleaning.R") # function symbol_synonyms is in cleaning.R
vec <- symbol_synonyms(colnames(genexp), verbose = T)
unknown_genes_idx <- which(is.na(vec))
vec <- vec[-unknown_genes_idx]
genexp <- genexp[-unknown_genes_idx] # 1340 x 14290
dim(genexp)
colnames(genexp) <- vec
```



```{r, message=F, warning=F, eval=F}
#average non-unique genes
#genexp <- covarianceSelection:::average_same_columns(genexp) # 1340 x 14246
genexp <- average_same_columns(genexp) # 1340 x 14237  # average_same_columns is in cleaning.R 
dim(genexp)

#remove samples from subregions that we don't have a region for
#region_subregion <- covarianceSelection::region_subregion
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\region_subregion.rda")
vec <- rownames(genexp)
subregion <- unlist(strsplit(vec,"\\."))[seq(2, length(vec)*4, 4)]
idx <- which(subregion %in% region_subregion$subregion)
genexp <- genexp[idx,] # 1294 x 14237
dim(genexp)
```



```{r, message=F, warning=F, eval=F}
####

#load tada dataset
#tada <- covarianceSelection::tada
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\tada.rda")
tada=tada
#match the order in both datasets
idx <- which(colnames(genexp) %in% tada$Gene)
genexp <- genexp[,idx] # 1294 x 13964
dim(genexp)
idx <- which(tada$Gene %in% colnames(genexp))
tada <- tada[idx,] # 13964 genes
#idx <- covarianceSelection::matching(tada$Gene, colnames(genexp))
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\misc.R")
idx <- matching(tada$Gene, colnames(genexp))  # matching is in misc.R
genexp <- genexp[,idx]

#dat_list <- covarianceSelection::extractor(genexp) # 212 partitions
dat_list <- extractor(genexp) # 212 partitions  # extractor is in cleaning.R 
dat_list <- lapply(dat_list, as.matrix, drop = F)

# remove partitions too small
idx <- which(sapply(dat_list, function(x){ifelse(nrow(x) >= 5, T, F)}))
dat_list <- dat_list[idx] # 125 partitions
dat_list <- lapply(dat_list, scale, scale = F)

#if(verbose) print(paste0("Dimension of genexp is: ", paste0(dim(genexp), collapse = ", ")))

#cleanup
#rm(list = c("brain_expression", "brain_genes", "idx", "vec", "region_subregion",
#            "subregion", "genexp", "unknown_genes_idx"))

#saveRDS(dat_list, file ="C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\dat_list.rds")
```