---
title: "dawn algorithm"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-09-06"
---

```{r, message=F, warning=F, eval=T}
## https://github.com/linnykos/covarianceSelection/blob/master/main/step3_pfc35_analysis.R
rm(list=ls())
set.seed(10)
fdr_cutoff <- 0.01
pthres <- 0.05
library(statnet)  # use network function 
library(ggpubr)  # combine two graphs 
#####
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\screen_res.RData")  # dat_list needs to be in screen_res.RData not in data_preparation.RData
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\graphicalModel.r")
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\graph_functions.r")
selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
dat_pfc35 <- do.call(rbind, dat_list[selected_idx]) # 107 x 3065
dim(dat_pfc35)
dat_pfc35 <- scale(dat_pfc35, scale = F)
dim(dat_pfc35)
```


```{r, message=F, warning=F, eval=F}

# estimate graphical model on PFC35 using cross-validated lasso for neighborhood selection
 res <- graphicalModel_range(dat_pfc35, 1:length(screening_res$primary), 
                                                  lambda_min = 0.01, lambda_max = 0.35, 
                                                  lambda_length = 30, verbose = T) 
#
# scale_vec_pfc35 <- sapply(res, function(x){covarianceSelection::compute_scale_free(as.matrix(x$adj_mat))})
 scale_vec_pfc35 <- sapply(res, function(x){compute_scale_free(as.matrix(x$adj_mat))}) # compute_scale_free is in graph_functions.r 
 edges_vec_pfc35 <- sapply(res, function(x){sum(as.matrix(x$adj_mat))/2})
 idx <- which.max(scale_vec_pfc35)

 adj_pfc35 <- as.matrix(res[[idx]]$adj_mat)
 stopifnot(all(dim(adj_pfc35) == nrow(tada)))
 #save(adj_pfc35, file ="C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\adj_pfc35.RData")
 
```



```{r, message=F, warning=F, eval=T}
# curate the adj_pfc35 by incorporating PPI information 
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\adj_pfc35.RData")  # load incidence matrix 
load("C:\\han\\Projects\\IntegratePPI\\string.keep_gene_level.RData")  # load pairwise protein interaction information  

### build incidence matrix, (i,j)=1 if there is a link between genes, i & j, and 0 otherwise
#string_incidence=matrix(0, nrow=nrow(adj_pfc35), ncol=nrow(adj_pfc35))
#for (i in 1:(nrow(adj_pfc35)-1))
#  for (j in (i+1):nrow(adj_pfc35))
#    if (string.keep_gene_level_new %>% filter(protein1_gene==colnames(dat_pfc35)[i], protein2_gene==colnames(dat_pfc35)[j]) %>% nrow()>0)
#      { 
#      cat(i, "th gene is running", "\n")
#      string_incidence[i,j]=1
#      string_incidence[j,i]=1
#     }
  
#save(string_incidence, file ="C:\\han\\Projects\\IntegratePPI\\string_incidence.RData")  
load("C:\\han\\Projects\\IntegratePPI\\string_incidence.RData")
        
###### combine estimated incidence matrix and string PPI information, a link between two genes exists if it appears in estimated incidence matrix or string PPI  
adj_string_combine_incidence=adj_pfc35+string_incidence
for (i in 1:(nrow(adj_string_combine_incidence)-1))
  for (j in (i+1):ncol(adj_string_combine_incidence))
    if (adj_string_combine_incidence[i,j]>1)
    {
      adj_string_combine_incidence[i,j]=1
      adj_string_combine_incidence[j,i]=1
    }


net=network(as.matrix(adj_string_combine_incidence), directed=FALSE) # https://web.stanford.edu/class/bios221/labs/networks/lab_7_networks.html
set.seed(1)          # make the plot look the same as mine
par(mar=rep(0,4))

plot(net, vertex.cex=0.15, rescale=F) # vextex.cex control the vertex size

#dev.off()


```

* adj_pfc35+string_incidence with 3756 links 


```{r, message=F, warning=F}
net=network(as.matrix(adj_pfc35), directed=FALSE) # https://web.stanford.edu/class/bios221/labs/networks/lab_7_networks.html
#nodeColors<-ifelse(rownames(adjacency_network) %in% Gene_selected,"red","black")

#png("C:\\Users\\hans\\OneDrive - Marquette University\\SCZ-DAWN\\Figures\\Constraint_genes_network.png")

set.seed(1)          # make the plot look the same as mine
par(mar=rep(0,4))
#para_size=0.1
#vertex.size=ifelse(rownames(adjacency_network) %in% Gene_selected,10,para_size)
#label.size=ifelse(rownames(adjacency_network) %in% Gene_selected,0.5,para_size)
#vertex.cex=ifelse(rownames(adjacency_network) %in% Gene_selected,1,para_size)
#labels=ifelse(rownames(adjacency_network) %in% Gene_selected, Gene_selected,"")


#plot(net, label=labels, vertex.col=nodeColors, label.col="blue", vertex.size=vertex.size, label.cex=label.size, #vertex.cex=vertex.cex) # vextex.cex control the vertex size

plot(net, vertex.cex=0.15, rescale=F) # vextex.cex control the vertex size

#dev.off()
```
* adj_pfc35 with 1886 links 


```{r, message=F, warning=F}
library(statnet)
net=network(as.matrix(string_incidence), directed=FALSE) # https://web.stanford.edu/class/bios221/labs/networks/lab_7_networks.html
#nodeColors<-ifelse(rownames(adjacency_network) %in% Gene_selected,"red","black")

#png("C:\\Users\\hans\\OneDrive - Marquette University\\SCZ-DAWN\\Figures\\Constraint_genes_network.png")

set.seed(1)          # make the plot look the same as mine
par(mar=rep(0,4))
#para_size=0.1
#vertex.size=ifelse(rownames(adjacency_network) %in% Gene_selected,10,para_size)
#label.size=ifelse(rownames(adjacency_network) %in% Gene_selected,0.5,para_size)
#vertex.cex=ifelse(rownames(adjacency_network) %in% Gene_selected,1,para_size)
#labels=ifelse(rownames(adjacency_network) %in% Gene_selected, Gene_selected,"")


#plot(net, label=labels, vertex.col=nodeColors, label.col="blue", vertex.size=vertex.size, label.cex=label.size, #vertex.cex=vertex.cex) # vextex.cex control the vertex size

plot(net, vertex.cex=0.15, rescale=F) # vextex.cex control the vertex size

#dev.off()
```

* string_incidence with 1872 links 




```{r, message=F, warning=F, eval=F}
# run the HMRF
fdr_cutoff <- 0.01
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\hmrf.r")
source("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\misc.r")
load("C:\\han\\Projects\\Multi_Omics\\data_in_MOBS\\adj_pfc35.RData")
seedindex <- rep(0, ncol(adj_pfc35))
seedindex[which(tada$dn.LoF >= 3)] <- 1

#hmrf_pfc35 <- covarianceSelection::hmrf(tada$pval.TADA, adj_pfc35, seedindex, pthres = pthres)
hmrf_pfc35 <- hmrf(tada$pval.TADA, adj_pfc35, seedindex, pthres = pthres)
#hmrf_pfc35 <- hmrf(tada$pval.TADA, adj_string_combine_incidence, seedindex, pthres = pthres)
#report_pfc35 <- covarianceSelection::report_results(tada$Gene, 1-hmrf_pfc35$post, tada$pval.TADA, hmrf_pfc35$Iupdate)
report_pfc35 <- report_results(tada$Gene, 1-hmrf_pfc35$post, tada$pval.TADA, hmrf_pfc35$Iupdate)
genes_pfc35 <- sort(as.character(report_pfc35$Gene[which(report_pfc35$FDR <= fdr_cutoff)]))

adj_pfc35 <- Matrix::Matrix(adj_pfc35, sparse = T)



########################

# plot(exp(seq(log(0.01), log(0.35), length.out = length(scale_vec_pfc35))), scale_vec_pfc35)
```


```{r, message=F, warning=F}
# plot two networks with same coordinates
library(igraph)
library(dplyr)
string_incidence_igraph=graph_from_incidence_matrix(string_incidence)  # convert to igraph https://igraph.org/r/doc/graph_from_incidence_matrix.html
V(string_incidence_igraph)$name <- paste0("Node", 1:7000)
Coords <- layout_with_fr(string_incidence_igraph) %>% 
  as_tibble %>%
    bind_cols(data_frame(names = names(V(string_incidence_igraph))))


adj_pfc35_igraph=graph_from_incidence_matrix(adj_pfc35)  # convert to igraph https://igraph.org/r/doc/graph_from_incidence_matrix.html

V(adj_pfc35_igraph)$name <- paste0("Node", 1:7000)

new_Coords=data_frame(names = names(V(adj_pfc35_igraph))) %>%  ### this is the key step, get the same coordinates from the first graph 
    left_join(Coords, by= "names")


min_value=min(Coords[,1:2], new_Coords[,2:3])
max_value=max(Coords[,1:2], new_Coords[,2:3])



g3=string_incidence_igraph%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(Coords[,1:2]), rescale=F, xlim=c(min_value,max_value),ylim=c(min_value,max_value), main="string")  

g1=string_incidence_igraph%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = layout.circle, rescale=F, main="string")


g4=adj_pfc35_igraph%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(new_Coords[,2:3]),rescale=F, xlim=c(min_value-10,max_value+10),ylim=c(min_value,max_value), main="adj_pfc35")

g2=adj_pfc35_igraph%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = layout.circle, rescale=F,  main="adj_pfc35")

combine_plot1=ggarrange(g1, g2,nrow=1)
```






```{r, echo=F,  message=F, warning=F, eval=F}
# plot graphs with same positions https://stackoverflow.com/questions/46139709/plot-two-igraph-networks-using-the-same-coordinates-and-same-placement-in-the-pl


library(igraph); library(dplyr)

#generate random graph
set.seed(500)
RandomGraph <- sample_gnm(1000, 2500)

#name nodes
V(RandomGraph)$name <- paste0("Node", 1:1000)

#Get the coordinates of the Nodes
Coords <- layout_with_fr(RandomGraph) %>% 
  as_tibble %>%
    bind_cols(data_frame(names = names(V(RandomGraph))))

#Delete random vertices
deletevertex <-sample( V(RandomGraph)$name, 400)

RandomGraph2 <-delete.vertices(RandomGraph, deletevertex)

#get the coordinates of the remaining Nodes
  NetCoords <- data_frame(names = names(V(RandomGraph2))) %>%
    left_join(Coords, by= "names")

#plot both graphs

#RandomGraph%>% 
#  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(Coords[,1:2]))

#RandomGraph2%>% 
#  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(NetCoords[,2:3]))

#They nodes have the same relationship to each other but are not laid out in the same position in the frame


RandomGraph%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(Coords[,1:2]),rescale=F,xlim=c(-25,30),ylim=c(-20,35))

RandomGraph2%>% 
  plot(.,vertex.size=.8, edge.arrow.size=.4, vertex.label = NA, layout = as.matrix(NetCoords[,2:3]),rescale=F,xlim=c(-25,30),ylim=c(-20,35))

```







```{r, echo=F, message=F, warning=F, eval=F}
#partial likelihood function
.partial_likelihood <- function(b, c, graph_term, i_vec){
  d <- length(i_vec)

  fv_fun <- function(i){
    new1 <- exp(b*i_vec[i] + c*i_vec[i]*graph_term[i])
    new2 <- exp(b*(1-i_vec[i]) + c*(1-i_vec[i])*graph_term[i])
    fvalue <- log(new1/(new1+new2))
  }

  sum(sapply(1:d, fv_fun))
}

##estimate Ising model parameters b,c
.optimize_bc <- function(func, adj, i_vec, times, tol = 1e-5){
  b <- 0; c <- 0

  graph_term <- i_vec%*%adj
  for (k in 1:times){
    b_new <- stats::optimize(func, c(-10, 0), c = c, graph_term = graph_term,
                             i_vec = i_vec, maximum = T)$maximum
    c_new <- stats::optimize(func, c(0.5, 5), b = b_new, graph_term = graph_term,
                             i_vec = i_vec, maximum = T)$maximum
    if (abs(b_new-b) < tol & abs(c_new-c) < tol){
      break()
    }

    b <- b_new; c <- c_new
  }

  list(b = b, c = c)
}


#' Hidden markov random field
#'
#' Use a Ising model to update the pvalues according to the graphical structure.
#' There are two groups, indices in group 0 have mean 0. Indices in group 1 have
#' mean greater than 0.
#'
#' @param pval a vector of d p-values, between 0 and 1.
#' @param adj a dxd adjancey matrix (0,1 entries)
#' @param seedindex a (0,1) vector of length d, where 1 means the gene is in group 1.
#' @param pthres threshold for p-values to serve as an initialization
#' @param iter number of iterations
#' @param verbose boolean
#' @param tol tolerance for values that should be treated as zero in absolute value
#'
#' @return a list
#' @export
hmrf <- function(pval, adj, seedindex, pthres = 0.05, iter = 100,
                 verbose = FALSE, tol = 1e-3){
  stopifnot(length(pval) == length(seedindex), all(dim(adj) == length(pval)))

  #permute all the entries to avoid emphasis on current order
  d <- length(pval)
  idx <- sample(1:d)
  pval <- pval[idx]; adj <- adj[idx,idx]; seedindex <- seedindex[idx]

  z <- stats::qnorm(1-pval)
  i_vec <- as.numeric(pval<pthres)
  b <- Inf; c <- Inf

  non_seedidx <- (seedindex==0)
  mu1 <- mean(z[i_vec==1 & non_seedidx])
  sigmas1 <- (stats::sd(z[i_vec == 0]))^2
  sigmas2 <- (stats::sd(z[i_vec == 1 & non_seedidx]))^2
  posterior <- rep(0,d)

  for (iteri in 1:iter){

    if(verbose) print(paste("Start iteration: ", iteri))
    res <- .optimize_bc(.partial_likelihood, adj, i_vec, 20)
    b_new <- res$b; c_new <- res$c

    if (abs(c-c_new)<tol & abs(b-b_new)<tol)  break()
    b <- b_new; c <- c_new

    for (i in 1:d){
      i_vec_tmp <- i_vec; i_vec_tmp[i] <- 1-i_vec[i]

      new1 <- b*i_vec[i] + c*i_vec[i]*adj[i,]%*%i_vec
      new2 <- b*(1-i_vec[i]) + c*(1-i_vec[i])*adj[i,]%*%i_vec_tmp
      p1 <- stats::dnorm(z[i], mu1*i_vec[i], sqrt(sigmas2 * i_vec[i] + sigmas1 * (1 - i_vec[i])))/(1 + exp(new2-new1))
      p2 <- stats::dnorm(z[i], mu1*(1-i_vec[i]), sqrt(sigmas2 * (1 - i_vec[i]) + sigmas1 * i_vec[i]))/(1 + exp(new1-new2))

      if (i_vec[i] == 1){
        posterior[i] <- p1/(p1+p2)
      } else {
        posterior[i] <- p2/(p1+p2)
      }

      if (p2 > p1){ i_vec[i] <- 1-i_vec[i] }
      if (seedindex[i] != 0){ i_vec[i] <- 1 }
    }

    mu1 <- sum(posterior[non_seedidx]*z[non_seedidx])/sum(posterior[non_seedidx])
    sigmas2 <- sum(posterior[non_seedidx]*(z[non_seedidx]-mu1)^2)/sum(posterior[non_seedidx])
    sigmas1 <- sum((1-posterior[non_seedidx])*(z[non_seedidx])^2)/sum(1-posterior[non_seedidx])
    sigmas <- (sigmas1*sum(posterior[non_seedidx]) + sigmas2*sum(1-posterior[non_seedidx])) / length(posterior[non_seedidx])
    sigmas1 <- sigmas; sigmas2 <- sigmas

    if(verbose) print(paste0("Iteration: ",iteri," has ", sum(i_vec)," genes set with Iupdate = 1."))
  }

  #un-permute the elements
  i_vec <- i_vec[order(idx)]; posterior <- posterior[order(idx)]
  
  if(verbose){
    if (!check_b(i_vec, b)) {
      cat('\n\nWARNING: DAWN identified a large number of risk genes. 
          Assumptions of the model may be false. 
          The set of risk genes likely contains many false positives.\n')
    }
    if (!check_c(adj, i_vec, b, c)) {
      cat('\n\nWARNING: Weak connectivity among risk genes in the input graph. 
          Assumptions of the model appear to be false. 
          The set of risk genes likely contains many false positives.\n')
    }
  }

  list(Iupdate = i_vec, post = posterior, b = b, c = c, mu1 = mu1, sigmas = sigmas)
}


## Check if b0 value is reasonable
## Input:
##      I - estimated hidden indicator vector
##      b0 - estimated b0
##      thres_b0 - threshold for evaluating b0
## Output:
##      pass - a boolean variable, True if b0 passes the test, False otherwise
check_b <- function(i_vec, b, thres_b = 0.05){
  ## Check if P(sum(I)>thres) < thres under the distribution that:
  ## P(sum(I)) ~ binom(n,exp(b0)/(1+exp(b0)))
  n <- length(i_vec)
  q <- floor(n * thres_b);
  p <- exp(b) / (1 + exp(b))
  tail_prob <- stats::pbinom(q = q, size=n, prob = p, lower.tail = F) ##P(sum(I)>thres)
  
  tail_prob < thres_b
}

## Check if b1 value is reasonable
## Input:
##      G - adjacency matrix for graph
##      I - estimated hidden indicator vector
##      b0 - estimated b0
##      b1 - estimated b1
##      thres_b1 - threshold for evaluating b1
## Output:
##      pass - a boolean variable, True if b0 passes the test, False otherwise
check_c <- function(adj, i_vec, b, c, thres_c = 0.1) {
  ## Check if b1*I'GI is significant comparing to b0*I
  as.numeric(abs(c*i_vec%*%adj%*%i_vec / (b*sum(i_vec)))) > thres_c
}


```
