---
title: "incidence matrix"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-09-12"
---

```{r, echo=F, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(dplyr)
library(tidyr)
```


```{r, message=F, warning=F, eval=F}
load("C:\\han\\Projects\\IntegratePPI\\tmp01_STRING_graph.Rdata") # load string data
incidence_matrix=ftM2adjM(as.matrix(string.keep[,1:2]))  # create  incidence matrix
# map to genes 
sfari.id = read.table("C:\\han\\Dataset\\20240610_PMID_33244169\\sfari_gene_ids.txt",sep="\t",stringsAsFactors=F,header=T)  # this file has both Gene symbol and protein stable ID !!!!!!!!!!!!

## build gene level incidence matrix 
#protein1_gene=sfari.id$Gene.name[which(string.keep$protein1 %in% sfari.id$Protein.stable.ID)]
find_gene=function(x)
{
  if (length(which(sfari.id$Protein.stable.ID==x))>0)
    return(sfari.id$Gene.name[which(sfari.id$Protein.stable.ID==x)[1]]) # use the first one if multiple returns
 if (length(which(sfari.id$Protein.stable.ID==x))==0)
   return(" ")
  
}

protein1_gene=unlist(sapply(string.keep$protein1, find_gene)) # length(protein1_gene)==nrow(string.keep)
protein2_gene=unlist(sapply(string.keep$protein2, find_gene))

string.keep_gene_level=data.frame(string.keep) %>%  mutate (protein1_gene=as.character(protein1_gene), protein2_gene=as.character(protein2_gene))
protein1_gene_index=which(string.keep_gene_level$protein1_gene!=" ")  # keep rows with valid gene names 
protein2_gene_index=which(string.keep_gene_level$protein2_gene!=" ")

string.keep_gene_level_new=string.keep_gene_level[intersect(protein1_gene_index, protein2_gene_index),]

#save(string.keep_gene_level_new, file="C:\\han\\Projects\\IntegratePPI\\string.keep_gene_level.RData")
```


```{r, message=F, warning=F}
load("C:\\han\\Projects\\IntegratePPI\\string.keep_gene_level.RData")


```